### ISSUE TITLE
Shortcuts are always rebound on VS startup Without Fail

### ISSUE THREAD

**Issue by aluanhaddad** [justcla/HotCommands#59]
Hi, thanks for writing this extension, I would like to continue to use it but unfortunately, there is an issue which makes it absolutely, maddeningly unusable for me.

Whenever I start Visual Studio, HotCommands **_rebinds_** all of its keybindings, recreating them even if they have been overwritten, changed, or removed.

I use a keyboard profile which is a derivative of the "Visual C# 2005" preset in Visual Studio and thus uses 
`Ctrl+W` as the first combination for chord based commands such as `View.Solution Explorer`, `View.TeamExplorer`, `View.Errors`, and so on. I defined `Ctrl+W, Ctrl + W` / `Ctrl+W, W`, as a shortcut for `Window.CloseDocumentWindow`. I mention this last one because HotCommands causes VS to throw a modal Error whenever I hit `Ctrl+W, Ctrl+W`.

Naturally, I have tried binding `Edit.IncreaseSelection` to a different hotkey and removing the assignment created by this extension. This has no lasting effect as it is recreated, without fail, each and every time I start VS as soon as I load any file. I have to remove the binding for `Ctrl+W` every time a start VS. 

This took me a while to track down because I have a fair number of extensions installed and because I frankly forgot that `Edit.IncreaseSelection` is a command created by this extension.

I am using Visual Studio 2017 RC, and am running Windows 10 Pro.

**Comment by aluanhaddad** [comment]
Glancing over the code it looks as though the overwriting is intentional under certain circumstances:
https://github.com/justcla/HotCommands/blob/28faf19ed462987fb77b1a3bdd49c84e9b0f613b/HotCommands/Commands/ExpandSelection.cs#L30

I think the following behavior would be reasonable:
Do not create a binding for any command when a key bound command with that name already exists. This would allow users to actually define their own mappings for HotCommands.

**Comment by justcla** [comment]
Hi Aluan. Thanks very much for your feedback.
I have to agree. It was pretty irresponsible of me to force take-over the Ctrl+W shortcut.
(Although it was a useful sample for programmatically working with keyboard shortcuts.)
I had to do it because Ctrl+W was being used.
At the time, I was comparing it with the Default keyboard mapping scheme, which used Ctrl+W at the (Text Editor) scope for Edit.SelectCurrentWord, so it was a similar function and thought it would be sensible.

However, I can see that Ctrl+W is the leading character for dozens of tool window shortcuts in the other mapping schemes, so it's a bold decision to sacrifice all those shortcuts for this one.

And I shouldn't have done that.
So I'm going to remove the manual override of the Ctrl+W shortcut for Edit.IncreaseSelection

Note: By defining shortcuts in the VSCT file, Visual Studio automatically applies that logic you mentioned wherein it will not apply any shortcut if those keys are already in use at the defined scope.

All the other shortcuts in HotCommands work through the VSCT file definitions.
We only had to introduce the force take-over for Ctrl+W because it was in use and I really wanted to replicate the behavior of the IDEA keyboard mapping scheme.

However, I don't want to leave the command with no assigned shortcut that works out of the box. Too many users will struggle (or not bother) to manually assign keyboard shortcuts to Increase/Decrease selection. So I'll replace it with something else.

Got any suggestions for the new default keyboard shortcuts (both increase and decrease selection)?

**Comment by justcla** [comment]
Ah... I can see now that I originally took care of that situation.

`            KeyBindingUtil.Initialize(package);
            // We only want to force this keyboard binding if it is currently set to the default VS shortcut
            // ie. Ctrl+W bound to Edit.SelectCurrentWord
            //if (KeyBindingUtil.BindingExists("Edit.SelectCurrentWord", "Text Editor::Ctrl+W"))
            //{
                KeyBindingUtil.BindShortcut("Edit.IncreaseSelection", "Text Editor::Ctrl+W");
            //}
`

I can see that on 30-Oct I checked turned off the checks - forcing it on all keyboard bindings.
(That might have been to work in with HotKeys mappings.)

**Comment by justcla** [comment]
How about Ctrl+{ as a chord?
{ } to expand
{ { to shrink.

Or, more technically:

    <KeyBinding guid="guidHotCommandsPackageCmdSet" id="cmdidExpandSelection" editor="GUID_TextEditorFactory" mod1="Control Shift" key1="VK_OEM_4" mod2="Control Shift" key2="VK_OEM_6"/>
    <KeyBinding guid="guidHotCommandsPackageCmdSet" id="cmdidShrinkSelection" editor="GUID_TextEditorFactory" mod1="Control Shift" key1="VK_OEM_4" mod2="Control Shift" key2="VK_OEM_4"/>

**Comment by aluanhaddad** [comment]
@justcla Thank you for your response and your willingness to address this issue.

For what it is worth, this is not the only extension that overrides common keyboard shortcuts. For example Apex SQL refactor overrides `Ctrl+Shift+B`, which is `Build.BuildSolution`!

I feel like the issue is partially one of discoverability, and more one of not being able to override the behavior.

I think `Ctrl+{` sounds great but then again I do not use that for anything personally.

Honestly if I could overwrite the mapping, I would be satisfied.

> Note: By defining shortcuts in the VSCT file, Visual Studio automatically applies that logic you mentioned wherein it will not apply any shortcut if those keys are already in use at the defined scope.

Perhaps this is a naive question (I am not familiar with authoring extensions) but would it not be possible overwrite conditionally on there not being any existing bindings for `Edit.IncreaseSelection` to any key? That way the key could be set initially, but then could be customized.

**Comment by justcla** [comment]
@aluanhaddad You're welcome.

Yes, I used conditional logic originally. We could use the logic to only set the shortcut key if it's not in use.

But then what happens if the keyboard binding schemes change?
Also I'm concerned about what other problems it might cause.
Hence I'm thinking of taking a much safer approach and not doing any forced keyboard binding at all.

Also, Ctrl+W is used on all the inbuilt keyboard mapping schemes. So it would never get bound.
I might as well pick a shortcut that people can use.

And, as you say, you can always manually bind it yourself (in Tools->Options->Keyboard)

**Comment by aluanhaddad** [comment]
Thank you!

**Comment by justcla** [comment]
Completed in commit #60 

New versions v1.1.5 uploaded to [Marketplace.](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotCommandsforVisualStudio)

New release available: https://github.com/justcla/HotCommands/releases/tag/v1.1.5

**Comment by aluanhaddad** [comment]
Thank you so much. Just installed v1.1.5 and it is working great ❤️
