### ISSUE TITLE
Duplicate selection needs this!

### ISSUE THREAD

**Issue by onolox** [justcla/HotCommands#89]
Hi, I detected a "problem" in the 2022 version of this plugin, example:

I select for example 3 lines, and select it in the middle like in the image attached.
When I use the command to duplicate it needs to duplicate the entire 3 lines, no only the selection.

![Capturar](https://user-images.githubusercontent.com/11450681/182042743-40a4bf8f-65e6-4026-a581-68aa22c16497.JPG)

The builtin command in VS duplicates the selection only, I think in the 2017 your extension duplicates the entire lines if they are partially selected.
This is the behavior of all editors that I can remember, and I think is a good thing to differentiate you plugin from the builtin from VS2022.

**Comment by justcla** [comment]
Both my extension, and the VS implementation follow the same behaviour as IntelliJ.

And without this behaviour, it's impossible to duplicate a section of a line or a segment that spans multiple lines.

At the time it was implemented by VS, @olegtk argued that it would be more useful if the partial selection over multiple lines duplicates the whole line for all lines that the selection touches (which is what you are suggesting, if I'm reading it right).

I have to agree with you and with Oleg that it's more useful more often if it duplicates the whole line. With the exception that a selection on a single line only duplicates the selection - this is basically how Toggle Comment works.

Perhaps the best solution is to provide two separate commands: DuplicateLine and DuplicateSelection.

**Comment by justcla** [comment]
I could implement it on HotCommands.
It's a pretty good suggestion. I would favour the "Option/Setting" solution.

But I don't have much time, and I was hoping to deprecate this command now that VS had y implemented it.

It would be much better for everyone if VS implemented it. I strongly urge you to put this suggestion into the VS feedback!! Tag Oleg and Christian and see if they can have a discussion about this.

Send me a link. I'll vote on it.

**Comment by onolox** [comment]
VS already have this built in, then this plugin doing something different is the best choice.
Edit.HotCommands.DuplicateLines

**Comment by justcla** [comment]
> your extension duplicates the entire lines if they are partially selected.
This is the behaviour of all editors that I can remember

Can you please help me find any program that operates this way?
I built this command based on **IntelliJ** behaviour.
The only time a Line is duplicated instead of the Selection is when there is no selection (ie. single blinking cursor on a line).
Every other time when there is a selection - either on a single line or over multiple lines - the behaviour is always to simply duplicate the selection.
They call the command "Duplicate Selection" when there is a selection, and "Duplicate Line" when there is no selection.

And **Visual Studio** implemented the same. (They just call it "Duplicate")
**Sublime** behaves the same as this, too (even though the command is called "Duplicate Line").
So does **VS Code**. They explicitly call the command "Duplicate Selection"

So, if you know of any programs that implement "Duplicate Line" behaviour when there is a non-empty selection, please share it with me.

**Comment by justcla** [comment]
The main reason I want to find other implementations is to see how to handle the selection.

If the selection is spanning half of one line and some of the last line, what should be selected after the operation is applied?
Should the new selection be the entire new text (beginning of line to the start of the line after the last)?
Or should the selection remain the same, with the lines partially selected?

And how do we handle multiple carets in the case where two or more selections exist on the one line?

**Comment by onolox** [comment]
The implementation is simple, if exists text in the start or end of the selections's line that are not selected AND is a multi line selection then duplicate the entire lines.
VS Code for example.

**Comment by justcla** [comment]
Hahaha. I think you mean the concept is simple. The implementation, is quite tricky. (Have you tried it? You are welcome to offer a Pull Request.) Finding the start point of the line is not easy while maintaining the caret in multiple selections. I'll spare you the implementation challenges. But, rest assured, if it was easy, I would have published it last night, instead of staying up until 4am struggling with VirtualSnapshot BufferPositions and ITextViewLine objects. 🤣😂

**Comment by justcla** [comment]
Anyway, getting back to my question - "Is there an example of software that does it this way?"
You mentioned VS Code for example. But VS Code only has the "Duplicate Selection" command. And it behaves exactly the same way as IntelliJ, Sublime, Visual Studio, and this extension. (Please check - in case I am mistaken. But I went to the effort of downloading, installing and testing VS Code to check its behaviour before I wrote my previous detailed reply.)

It seems there is no software out there (that we can find) that offers a DuplicateLine command for a non-empty selection.
If you find one, please let me know.

**Comment by justcla** [comment]
Regardless, if I will be the first to implement this (and show the Visual Studio Editor team how it's done), then I need to decide how to handle the selection after the operation.

A. No text is selected. Existing selections lost. Caret sits at the end of the new line/s.
B. The same text that was previously selected in the original line/s is now selected in the new lines.
C. The entire text of the new line/s is now the selection.

A is the easiest to implement. This is basically what you showed on the reply to the VS Feedback item.
It's sloppy. It loses all the selection. It's then a real pain for the user to re-select text again.

Personally, I think B is the least disruptive for the user. It keeps every selection and every caret exactly where it was, but now on new lines.

But C might be useful on some occasions. If you wanted to "create" new lines in the code, you might immediately want to work with those new lines, so having the entire line selected might be what's desired. But a user can more easily expand a selection to the whole line than they can reduce the selection to some user-specified point, so it's likely to be a pain.

I will try to go for option B. This is kind of what happens in Visual Studio when you call ToggleLineComment while you have a selection. The selection maintains throughout the operation.

**Comment by justcla** [comment]
I've created the command (DuplicateLines) and bound it to Ctrl+Shift+D.
It is now available on Marketplace, and in [this repo as v4.1.0](https://github.com/justcla/HotCommands/releases/download/v4.1.0/HotCommands-v4.1.0.vsix)

Enjoy!

**Comment by onolox** [comment]
The Code example, I forgot to mention, the shortcut is for the command Copy Line down.
The selection is not really needed because the selection of the lines is for the duplicate the entire lines. But if you maintain the selection, ok.

The use case of select partially 2 or more lines and only have this selection duplicated have little to no real use case in my opinion, makes no sense.

**Comment by justcla** [comment]
Did you try the command that I built?
Does it work for you?

**Comment by justcla** [comment]
Thanks for pointing out the Copy Line Down (and I found Copy Line Up, which is much the same).
I tested Copy Line Down in VS Code.
It turns out that my implementation is exactly the same - with respect to selection, and also handling the end of selection on the first char in a line.

We should probably mention the VS Code "Code Line Down" command in the Visual Studio feedback ticket that you raised. It will help them.

And now we can also point them to Hot Commands. 😉

**Comment by justcla** [comment]
IntelliJ call this command "Duplicate Entire Lines". It has no default shortcut and doesn't appear on the Edit menu.
The behaviour is the same as "Copy Lines Down", except the handling of selection is not consistent. When any non-zero selection is duplicated, the resultant lines are fully selected, with the caret blinking in it's original position (meaning it's often/usually inside the middle of the selection).

**Comment by onolox** [comment]
Hi, working perfectly.
Thanks.
